---
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: UniFi Network Application"
  org.opencontainers.image.description: "Provides Ubiquiti Networks' UniFi Network Application software, which allows you to manage your UniFi network via the web browser."
  org.opencontainers.image.source: "https://github.com/blaubaer/ha-addon-unifi"
  org.opencontainers.image.url: "https://github.com/blaubaer/ha-addon-unifi"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.vendor: "Gregor Noczinski"
  org.opencontainers.image.authors: "Franck Nijhof <frenck@addons.community>, Gregor Noczinski <gregor@noczinski.eu>"
  org.opencontainers.image.documentation: "https://github.com/blaubaer/ha-addon-unifi/blob/mainmain/README.md"