on:
  pull_request:
    types:
      - opened
      - assigned
      - closed
      - edited
      - labeled
      - locked
      - reopened
      - unlabeled
      - unlocked
      - unassigned
      - converted_to_draft

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          set -ex
          echo "${{ toJson(github) }}"
